name: compilazione relazione

on:
  push:
    branches:
      - "*"

jobs:
  compilazione:
    runs-on: ubuntu-latest

    steps:
      - name: passo1 installazione typst
        uses: Homebrew/actions/setup-homebrew@master
      - name: passo2 installazione typst
        run: |
          brew install typst
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compilazione
        run: |
          typst compile DocsSrc/main.typ relazione.pdf --font-path=assets/fonts
      - name: Add and commit
        run: |
          git add relazione.pdf
          git commit -m "Relazione compilata"
          git push
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
