name: Download

on:
  push:
    branches:
      - '*'

jobs:
  esegui-azione:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Comprimi progetto
        run: tar -czf progetto-tecweb.tar.gz .

      - name: Carica l'artefatto
        uses: actions/upload-artifact@v3
        with:
          name: Festival
          path: progetto-tecweb.tar.gz
